In [7]:
import pandas as pd

df = pd.read_csv("../01_data/raw/week_2_3_exam_student_signals.csv")

df.head()

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76
3,2026IT002,Divya,Information Technology,55,4,3,46,52
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82

In [2]:
print("Before:", df.shape)

df = df.drop_duplicates()

print("After:", df.shape)

Before: (8, 8)
After: (8, 8)

In [4]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna("Unknown")

for col in df.select_dtypes(include=["int64", "float64"]).columns:
    df[col] = df[col].fillna(df[col].mean())

In [5]:
df["Total Score"] = df["assignment_score"] + df["lab_score"]

df["Performance"] = df["attendance_pct"].apply(
    lambda x: "Good" if x >= 75 else "Needs Improvement"
)

df.head()

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score,Total Score,Performance
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88,172,Good
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61,119,Needs Improvement
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76,148,Good
3,2026IT002,Divya,Information Technology,55,4,3,46,52,98,Needs Improvement
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82,161,Good

In [6]:
import os

os.makedirs("../01_data/processed", exist_ok=True)

df.to_csv("../01_data/processed/dataforge_cleaned.csv", index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!

In [8]:
print("Before:", df.shape)

df = df.drop_duplicates()

print("After:", df.shape)

Before: (8, 8)
After: (8, 8)

In [9]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna("Unknown")

for col in df.select_dtypes(include=["int64", "float64"]).columns:
    df[col] = df[col].fillna(df[col].mean())

In [10]:
df["Total Score"] = df["assignment_score"] + df["lab_score"]

df["Performance"] = df["attendance_pct"].apply(
    lambda x: "Good" if x >= 75 else "Needs Improvement"
)

df.head()

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score,Total Score,Performance
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88,172,Good
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61,119,Needs Improvement
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76,148,Good
3,2026IT002,Divya,Information Technology,55,4,3,46,52,98,Needs Improvement
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82,161,Good

In [11]:
import os

os.makedirs("../01_data/processed", exist_ok=True)

df.to_csv("../01_data/processed/dataforge_cleaned.csv", index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!

In [12]:
print("Before:", df.shape)

df = df.drop_duplicates()

print("After:", df.shape)

Before: (8, 10)
After: (8, 10)

In [13]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna("Unknown")

for col in df.select_dtypes(include=["int64", "float64"]).columns:
    df[col] = df[col].fillna(df[col].mean())

In [14]:
df["Total Score"] = df["assignment_score"] + df["lab_score"]

df["Performance"] = df["attendance_pct"].apply(
    lambda x: "Good" if x >= 75 else "Needs Improvement"
)

df.head()

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score,Total Score,Performance
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88,172,Good
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61,119,Needs Improvement
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76,148,Good
3,2026IT002,Divya,Information Technology,55,4,3,46,52,98,Needs Improvement
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82,161,Good

In [15]:
import os

os.makedirs("../01_data/processed", exist_ok=True)

df.to_csv("../01_data/processed/dataforge_cleaned.csv", index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!