In [1]:
import pandas as pd

df = pd.read_csv("../01_data/processed/dataforge_cleaned.csv")

df.head()

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score,Total Score,Performance
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88,172,Good
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61,119,Needs Improvement
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76,148,Good
3,2026IT002,Divya,Information Technology,55,4,3,46,52,98,Needs Improvement
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82,161,Good

In [2]:
import os

os.makedirs("../03_visuals", exist_ok=True)

numeric_summary = df.describe().T

numeric_summary.to_csv("../03_visuals/numeric_summary.csv")

numeric_summary

,count,mean,std,min,25%,50%,75%,max
attendance_pct,8.0,73.375,18.700172,43.0,61.75,74.5,89.00,96.0
diary_entries,8.0,8.125,4.015595,2.0,5.50,8.5,10.50,14.0
tasks_completed,8.0,6.000,2.507133,2.0,4.50,6.5,8.00,9.0
assignment_score,8.0,66.375,19.190306,35.0,55.00,69.0,80.25,91.0
lab_score,8.0,70.375,18.228216,41.0,58.75,72.5,83.50,94.0
Total Score,8.0,136.750,37.407982,76.0,113.75,141.5,163.75,185.0

In [3]:
missing = (df.isna().mean() * 100).sort_values(ascending=False)

missing.to_csv("../03_visuals/missing_percent.csv")

missing

student_id          0.0
name                0.0
department          0.0
attendance_pct      0.0
diary_entries       0.0
tasks_completed     0.0
assignment_score    0.0
lab_score           0.0
Total Score         0.0
Performance         0.0
dtype: float64

In [4]:
df.groupby("department")["attendance_pct"].mean()

department
Civil Engineering         79.500000
Computer Engineering      84.000000
Information Technology    58.666667
Name: attendance_pct, dtype: float64

In [5]:
df.groupby("department")["assignment_score"].mean()

department
Civil Engineering         72.500000
Computer Engineering      77.666667
Information Technology    51.000000
Name: assignment_score, dtype: float64

In [6]:
df.groupby("department")["lab_score"].mean()

department
Civil Engineering         75.500000
Computer Engineering      81.000000
Information Technology    56.333333
Name: lab_score, dtype: float64

In [7]:
df.groupby("Performance")["Total Score"].mean()

Performance
Good                 166.5
Needs Improvement    107.0
Name: Total Score, dtype: float64

In [8]:
top10 = df.nlargest(10, "Total Score")

top10

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score,Total Score,Performance
6,2026CS003,Gauri,Computer Engineering,96,14,9,91,94,185,Good
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88,172,Good
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82,161,Good
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76,148,Good
5,2026CE002,Fatima,Civil Engineering,71,8,6,66,69,135,Needs Improvement
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61,119,Needs Improvement
3,2026IT002,Divya,Information Technology,55,4,3,46,52,98,Needs Improvement
7,2026IT003,Harshada,Information Technology,43,2,2,35,41,76,Needs Improvement

In [9]:
bottom10 = df.nsmallest(10, "Total Score")

bottom10

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score,Total Score,Performance
7,2026IT003,Harshada,Information Technology,43,2,2,35,41,76,Needs Improvement
3,2026IT002,Divya,Information Technology,55,4,3,46,52,98,Needs Improvement
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61,119,Needs Improvement
5,2026CE002,Fatima,Civil Engineering,71,8,6,66,69,135,Needs Improvement
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76,148,Good
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82,161,Good
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88,172,Good
6,2026CS003,Gauri,Computer Engineering,96,14,9,91,94,185,Good